// <auto-generated />
using System;
using ContactWebApi.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactWebApi.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20191212120306_ContactWebApi.Dal.ContactContext")]
    partial class ContactWebApiDalContactContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactWebApi.Entity.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ContactWebApi.Entity.EmailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContactEntityId")
                        .HasColumnType("int");

                    b.Property<string>("MailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactEntityId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("ContactWebApi.Entity.PhoneNumberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContactEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactEntityId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("ContactWebApi.Entity.EmailEntity", b =>
                {
                    b.HasOne("ContactWebApi.Entity.ContactEntity", "ContactEntity")
                        .WithMany("Emails")
                        .HasForeignKey("ContactEntityId");
                });

            modelBuilder.Entity("ContactWebApi.Entity.PhoneNumberEntity", b =>
                {
                    b.HasOne("ContactWebApi.Entity.ContactEntity", "ContactEntity")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ContactEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
